staticSites:
  - name: AltMatchFront
    staticPublishPath: front/dist
    routes:
      - source: ^/assets/(.*)
        destination: /assets/$1
      - source: ^/(.*)
        destination: /index.html